local nio = require("nio")
local lsp = require("neotest-java.lsp")
local logger = require("neotest-java.logger")

local M = {}

---@param additional_classpath_entries string[]
---@param dir string
M.get_classpaths = function(additional_classpath_entries, dir)
    additional_classpath_entries = additional_classpath_entries or {}

    local bufnr = nio.api.nvim_get_current_buf()
    local uri = vim.uri_from_fname(dir)

    local results = { ["runtime"] = {}, ["test"] = {} }
    for scope, _ in pairs(results) do
        local options = vim.json.encode({ scope = scope })
        local args = {
            command = "java.project.getClasspaths",
            arguments = { uri, options },
        }
        local err, result = lsp.execute_command("workspace/executeCommand", args, bufnr)
        assert(not err, vim.inspect(err))

        -- Note:
        -- 1) module paths are not duplicated on the classpath,
        -- 2) the classpath and modulepath generated by the eclipse jdtls, do
        -- not include the target/test-classes directory, for maven projects
        -- using the Java Platform Module System.

        if next(result.modulepaths) ~= nil then
            logger.error(
                "Java Platform Module System not supported. Temporarily remove "
                .. "module-info.java for the test duration. modulepath="
                .. vim.inspect(result.modulepaths)
            )
        end
        results[scope] = result.classpaths
    end

    local runtime_classpaths = results.runtime
    local test_classpaths = results.test

    local classpaths = {}
    for _, v in ipairs(additional_classpath_entries) do
        classpaths[#classpaths + 1] = v
    end
    for _, v in ipairs(runtime_classpaths) do
        classpaths[#classpaths + 1] = v
    end
    for _, v in ipairs(test_classpaths) do
        classpaths[#classpaths + 1] = v
    end

    logger.debug(("classpath entries: %d"):format(#classpaths))
    return classpaths
end

return M
