local logger = require("neotest-java.logger")
local nio = require("nio")

--- @param deps { client_provider: fun(cwd: neotest-java.Path): vim.lsp.Client }
--- @return NeotestJavaCompiler
local function LspCompiler(deps)
	return {
		compile = function(args)
			local client = deps.client_provider(args.base_dir)

			logger.debug(("compilation in %s mode"):format(args.compile_mode))

			nio.run(function()
				client:request(
					"java/buildWorkspace",
					{ forceRebuild = args.compile_mode == "full" },
					function(err, result)
						if err then
							logger.error("compilation failed: " .. vim.inspect(err))
						end

						-- NOTE:
						-- 1) module paths are not duplicated on the classpath,
						-- 2) the classpath and modulepath generated by the eclipse jdtls, do
						-- not include the target/test-classes directory, for maven projects
						-- using the Java Platform Module System.
						if next(result.modulepaths) ~= nil then
							logger.error(
								"Java Platform Module System not supported. Temporarily remove "
									.. "module-info.java for the test duration. modulepath="
									.. vim.inspect(result.modulepaths)
							)
						end
					end
				)
			end)

			logger.debug("compilation complete!")
		end,
	}
end

return LspCompiler
