local logger = require("neotest-java.logger")

---@diagnostic disable-next-line: undefined-doc-name
--- @class neotest-java.JdtlsCompileDeps
--- @field client_provider fun(cwd: neotest-java.Path): vim.lsp.Client
--- @field schedule? fun(fn: fun()) Defaults to vim.schedule. Inject a synchronous pass-through in tests.

--- @param deps neotest-java.JdtlsCompileDeps
--- @return { compile: fun(opts: { base_dir: neotest-java.Path, compile_mode: "full" | "incremental" }) }
local function JdtlsCompile(deps)
	deps = deps or {}
	assert(deps.client_provider, "JdtlsCompile requires a client_provider")
	local schedule = deps.schedule or vim.schedule

	--- @param opts { base_dir: neotest-java.Path, compile_mode: "full" | "incremental" }
	local function compile(opts)
		local client = deps.client_provider(opts.base_dir)
		if not client or not client.initialized then
			return
		end

		logger.debug(("compilation in %s mode"):format(opts.compile_mode))

		schedule(function()
			--- @diagnostic disable-next-line: undefined-field
			client:request("java/buildWorkspace", { forceRebuild = opts.compile_mode == "full" }, function(err, result)
				if err then
					logger.error("compilation failed: " .. vim.inspect(err))
				end

				-- NOTE:
				-- 1) module paths are not duplicated on the classpath,
				-- 2) the classpath and modulepath generated by the eclipse jdtls, do
				-- not include the target/test-classes directory, for maven projects
				-- using the Java Platform Module System.
				if next(result.modulepaths) ~= nil then
					logger.error(
						"Java Platform Module System not supported. Temporarily remove "
							.. "module-info.java for the test duration. modulepath="
							.. vim.inspect(result.modulepaths)
					)
				end
			end)
		end)

		logger.debug("compilation complete!")
	end

	return {
		compile = compile,
	}
end

return JdtlsCompile
