name: CI

on:
  push:
    branches: ["main"]
    paths:
      - "lua/**"
      - "tests/**"
      - "scripts/**"
      - "*.lua"
      - "Makefile"
      - ".github/workflows/**"

jobs:
  test:
    uses: ./.github/workflows/test.yml

  e2e-test:
    uses: ./.github/workflows/e2e-test.yml
