name: CI

on:
  schedule:
    - cron: "00 00 * * 4" # every friday at 00:00
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true

      - name: Run tests
        run: make test
