name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Neovim
    - run: ./scripts/install-neovim

    - uses: actions/checkout@v3
    - name: Install dependencies
    - run: make install

    - uses: actions/checkout@v3
    - name: Run tests
    - run: make test

